package com.mckj.junkCode.templates.add

import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Template16
 *
 * @author mmxm
 * @date 2023/7/11 15:49
 */
object Template16 {
    fun fillfromCode(methodVisitor: MethodVisitor) {
        methodVisitor.visitCode()
        val label0 = Label()
        val label1 = Label()
        val label2 = Label()
        methodVisitor.visitTryCatchBlock(
            label0,
            label1,
            label2,
            "java/lang/ArrayIndexOutOfBoundsException"
        )
        methodVisitor.visitTryCatchBlock(
            label0,
            label1,
            label2,
            "java/lang/NegativeArraySizeException"
        )
        val label3 = Label()
        methodVisitor.visitLabel(label3)
        methodVisitor.visitLineNumber(894, label3)
        methodVisitor.visitLdcInsn("abcdefthijklmnopqrstuvwxyz")
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/lang/String",
            "toCharArray",
            "()[C",
            false
        )
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 1)
        val label4 = Label()
        methodVisitor.visitLabel(label4)
        methodVisitor.visitLineNumber(895, label4)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 2)
        val label5 = Label()
        methodVisitor.visitLabel(label5)
        methodVisitor.visitLineNumber(896, label5)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 1)
        methodVisitor.visitInsn(Opcodes.ARRAYLENGTH)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 3)
        val label6 = Label()
        methodVisitor.visitLabel(label6)
        methodVisitor.visitLineNumber(899, label6)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 10)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 5)
        val label7 = Label()
        methodVisitor.visitLabel(label7)
        methodVisitor.visitLineNumber(901, label7)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
        val label8 = Label()
        methodVisitor.visitLabel(label8)
        methodVisitor.visitLineNumber(902, label8)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 7)
        val label9 = Label()
        methodVisitor.visitLabel(label9)
        methodVisitor.visitLineNumber(903, label9)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        val label10 = Label()
        methodVisitor.visitLabel(label10)
        methodVisitor.visitLineNumber(904, label10)
        methodVisitor.visitInsn(Opcodes.ACONST_NULL)
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 10)
        methodVisitor.visitLabel(label0)
        methodVisitor.visitLineNumber(906, label0)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 11)
        val label11 = Label()
        methodVisitor.visitLabel(label11)
        methodVisitor.visitLineNumber(907, label11)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 2)
        methodVisitor.visitInsn(Opcodes.CALOAD)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 45)
        val label12 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label12)
        val label13 = Label()
        methodVisitor.visitLabel(label13)
        methodVisitor.visitLineNumber(908, label13)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 11)
        val label14 = Label()
        methodVisitor.visitLabel(label14)
        methodVisitor.visitLineNumber(909, label14)
        methodVisitor.visitIincInsn(2, 1)
        val label15 = Label()
        methodVisitor.visitLabel(label15)
        methodVisitor.visitLineNumber(910, label15)
        methodVisitor.visitIincInsn(3, -1)
        val label16 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label16)
        methodVisitor.visitLabel(label12)
        methodVisitor.visitLineNumber(911, label12)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 2)
        methodVisitor.visitInsn(Opcodes.CALOAD)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 43)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label16)
        val label17 = Label()
        methodVisitor.visitLabel(label17)
        methodVisitor.visitLineNumber(912, label17)
        methodVisitor.visitIincInsn(2, 1)
        val label18 = Label()
        methodVisitor.visitLabel(label18)
        methodVisitor.visitLineNumber(913, label18)
        methodVisitor.visitIincInsn(3, -1)
        methodVisitor.visitLabel(label16)
        methodVisitor.visitLineNumber(915, label16)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 12)
        val label19 = Label()
        methodVisitor.visitLabel(label19)
        methodVisitor.visitLineNumber(916, label19)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 13)
        val label20 = Label()
        methodVisitor.visitLabel(label20)
        methodVisitor.visitLineNumber(918, label20)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/util/Random")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/util/Random",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/util/Random",
            "nextBoolean",
            "()Z",
            false
        )
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 16)
        val label21 = Label()
        methodVisitor.visitLabel(label21)
        methodVisitor.visitLineNumber(919, label21)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 17)
        val label22 = Label()
        methodVisitor.visitLabel(label22)
        methodVisitor.visitLineNumber(920, label22)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 16)
        val label23 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label23)
        val label24 = Label()
        methodVisitor.visitLabel(label24)
        methodVisitor.visitLineNumber(921, label24)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        val label25 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFLE, label25)
        val label26 = Label()
        methodVisitor.visitLabel(label26)
        methodVisitor.visitLineNumber(922, label26)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 2)
        methodVisitor.visitInsn(Opcodes.CALOAD)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 15)
        val label27 = Label()
        methodVisitor.visitLabel(label27)
        methodVisitor.visitLineNumber(923, label27)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 48)
        val label28 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label28)
        val label29 = Label()
        methodVisitor.visitLabel(label29)
        methodVisitor.visitLineNumber(924, label29)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        val label30 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label30)
        val label31 = Label()
        methodVisitor.visitLabel(label31)
        methodVisitor.visitLineNumber(925, label31)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
        val label32 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label32)
        methodVisitor.visitLabel(label30)
        methodVisitor.visitLineNumber(926, label30)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitInsn(Opcodes.LCMP)
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label32)
        val label33 = Label()
        methodVisitor.visitLabel(label33)
        methodVisitor.visitLineNumber(927, label33)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitLdcInsn(10L)
        methodVisitor.visitInsn(Opcodes.LMUL)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        val label34 = Label()
        methodVisitor.visitLabel(label34)
        methodVisitor.visitLineNumber(928, label34)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitLabel(label32)
        methodVisitor.visitLineNumber(930, label32)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label35 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label35)
        val label36 = Label()
        methodVisitor.visitLabel(label36)
        methodVisitor.visitLineNumber(931, label36)
        methodVisitor.visitIincInsn(7, 1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label35)
        methodVisitor.visitLabel(label28)
        methodVisitor.visitLineNumber(932, label28)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 49)
        val label37 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPLT, label37)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 57)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPGT, label37)
        val label38 = Label()
        methodVisitor.visitLabel(label38)
        methodVisitor.visitLineNumber(933, label38)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 48)
        methodVisitor.visitInsn(Opcodes.ISUB)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 18)
        val label39 = Label()
        methodVisitor.visitLabel(label39)
        methodVisitor.visitLineNumber(934, label39)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        val label40 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label40)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitInsn(Opcodes.LCMP)
        val label41 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label41)
        methodVisitor.visitLabel(label40)
        methodVisitor.visitLineNumber(935, label40)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitLabel(label41)
        methodVisitor.visitLineNumber(936, label41)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitLdcInsn(10L)
        methodVisitor.visitInsn(Opcodes.LMUL)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 18)
        methodVisitor.visitInsn(Opcodes.I2L)
        methodVisitor.visitInsn(Opcodes.LADD)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        val label42 = Label()
        methodVisitor.visitLabel(label42)
        methodVisitor.visitLineNumber(937, label42)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label43 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label43)
        val label44 = Label()
        methodVisitor.visitLabel(label44)
        methodVisitor.visitLineNumber(938, label44)
        methodVisitor.visitIincInsn(7, 1)
        methodVisitor.visitLabel(label43)
        methodVisitor.visitLineNumber(939, label43)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label35)
        methodVisitor.visitLabel(label37)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 46)
        val label45 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label45)
        val label46 = Label()
        methodVisitor.visitLabel(label46)
        methodVisitor.visitLineNumber(941, label46)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label47 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label47)
        val label48 = Label()
        methodVisitor.visitLabel(label48)
        methodVisitor.visitLineNumber(942, label48)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label47)
        methodVisitor.visitLineNumber(943, label47)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 12)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label35)
        methodVisitor.visitLabel(label45)
        methodVisitor.visitLineNumber(944, label45)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            "java/lang/Character",
            "isDigit",
            "(C)Z",
            false
        )
        val label49 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label49)
        val label50 = Label()
        methodVisitor.visitLabel(label50)
        methodVisitor.visitLineNumber(945, label50)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 10)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            "java/lang/Character",
            "digit",
            "(CI)I",
            false
        )
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 18)
        val label51 = Label()
        methodVisitor.visitLabel(label51)
        methodVisitor.visitLineNumber(946, label51)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 18)
        val label52 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label52)
        val label53 = Label()
        methodVisitor.visitLabel(label53)
        methodVisitor.visitLineNumber(947, label53)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        val label54 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label54)
        val label55 = Label()
        methodVisitor.visitLabel(label55)
        methodVisitor.visitLineNumber(948, label55)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
        val label56 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label56)
        methodVisitor.visitLabel(label54)
        methodVisitor.visitLineNumber(949, label54)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitInsn(Opcodes.LCMP)
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label56)
        val label57 = Label()
        methodVisitor.visitLabel(label57)
        methodVisitor.visitLineNumber(950, label57)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitLdcInsn(10L)
        methodVisitor.visitInsn(Opcodes.LMUL)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        val label58 = Label()
        methodVisitor.visitLabel(label58)
        methodVisitor.visitLineNumber(951, label58)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label56)
        methodVisitor.visitLabel(label52)
        methodVisitor.visitLineNumber(954, label52)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        val label59 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label59)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitInsn(Opcodes.LCONST_0)
        methodVisitor.visitInsn(Opcodes.LCMP)
        val label60 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label60)
        methodVisitor.visitLabel(label59)
        methodVisitor.visitLineNumber(955, label59)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitLabel(label60)
        methodVisitor.visitLineNumber(956, label60)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitLdcInsn(10L)
        methodVisitor.visitInsn(Opcodes.LMUL)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 18)
        methodVisitor.visitInsn(Opcodes.I2L)
        methodVisitor.visitInsn(Opcodes.LADD)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        methodVisitor.visitLabel(label56)
        methodVisitor.visitLineNumber(958, label56)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label61 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label61)
        val label62 = Label()
        methodVisitor.visitLabel(label62)
        methodVisitor.visitLineNumber(959, label62)
        methodVisitor.visitIincInsn(7, 1)
        methodVisitor.visitLabel(label61)
        methodVisitor.visitLineNumber(960, label61)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label35)
        methodVisitor.visitLabel(label49)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 101)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label25)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 69)
        val label63 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label63)
        val label64 = Label()
        methodVisitor.visitLabel(label64)
        methodVisitor.visitLineNumber(963, label64)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label25)
        methodVisitor.visitLabel(label63)
        methodVisitor.visitLineNumber(965, label63)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label35)
        methodVisitor.visitLineNumber(921, label35)
        methodVisitor.visitIincInsn(2, 1)
        methodVisitor.visitIincInsn(3, -1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label24)
        methodVisitor.visitLabel(label25)
        methodVisitor.visitLineNumber(968, label25)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        val label65 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label65)
        val label66 = Label()
        methodVisitor.visitLabel(label66)
        methodVisitor.visitLineNumber(969, label66)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label65)
        methodVisitor.visitLineNumber(972, label65)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 11)
        val label67 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label67)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitInsn(Opcodes.LNEG)
        val label68 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label68)
        methodVisitor.visitLabel(label67)
        methodVisitor.visitVarInsn(Opcodes.LLOAD, 8)
        methodVisitor.visitLabel(label68)
        methodVisitor.visitVarInsn(Opcodes.LSTORE, 8)
        val label69 = Label()
        methodVisitor.visitLabel(label69)
        methodVisitor.visitLineNumber(973, label69)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 18)
        val label70 = Label()
        methodVisitor.visitLabel(label70)
        methodVisitor.visitLineNumber(974, label70)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 18)
        methodVisitor.visitInsn(Opcodes.ISUB)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 19)
        val label71 = Label()
        methodVisitor.visitLabel(label71)
        methodVisitor.visitLineNumber(977, label71)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label1)
        methodVisitor.visitLabel(label23)
        methodVisitor.visitLineNumber(978, label23)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitIntInsn(Opcodes.NEWARRAY, Opcodes.T_CHAR)
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 18)
        val label72 = Label()
        methodVisitor.visitLabel(label72)
        methodVisitor.visitLineNumber(979, label72)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        val label73 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFLE, label73)
        val label74 = Label()
        methodVisitor.visitLabel(label74)
        methodVisitor.visitLineNumber(980, label74)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 2)
        methodVisitor.visitInsn(Opcodes.CALOAD)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 15)
        val label75 = Label()
        methodVisitor.visitLabel(label75)
        methodVisitor.visitLineNumber(982, label75)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 48)
        val label76 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPLT, label76)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 57)
        val label77 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPLE, label77)
        methodVisitor.visitLabel(label76)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            "java/lang/Character",
            "isDigit",
            "(C)Z",
            false
        )
        val label78 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label78)
        methodVisitor.visitLabel(label77)
        methodVisitor.visitLineNumber(985, label77)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 48)
        val label79 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label79)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 10)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            "java/lang/Character",
            "digit",
            "(CI)I",
            false
        )
        val label80 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label80)
        methodVisitor.visitLabel(label79)
        methodVisitor.visitLineNumber(986, label79)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        val label81 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label81)
        val label82 = Label()
        methodVisitor.visitLabel(label82)
        methodVisitor.visitLineNumber(987, label82)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 18)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 17)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitInsn(Opcodes.CASTORE)
        val label83 = Label()
        methodVisitor.visitLabel(label83)
        methodVisitor.visitLineNumber(988, label83)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
        val label84 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label84)
        methodVisitor.visitLabel(label81)
        methodVisitor.visitLineNumber(989, label81)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 17)
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label84)
        val label85 = Label()
        methodVisitor.visitLabel(label85)
        methodVisitor.visitLineNumber(990, label85)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 18)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 17)
        methodVisitor.visitIincInsn(17, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitInsn(Opcodes.CASTORE)
        val label86 = Label()
        methodVisitor.visitLabel(label86)
        methodVisitor.visitLineNumber(991, label86)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label84)
        methodVisitor.visitLabel(label80)
        methodVisitor.visitLineNumber(994, label80)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        val label87 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label87)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 17)
        val label88 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label88)
        methodVisitor.visitLabel(label87)
        methodVisitor.visitLineNumber(995, label87)
        methodVisitor.visitIincInsn(6, 1)
        methodVisitor.visitLabel(label88)
        methodVisitor.visitLineNumber(996, label88)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 18)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 17)
        methodVisitor.visitIincInsn(17, 1)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitInsn(Opcodes.CASTORE)
        methodVisitor.visitLabel(label84)
        methodVisitor.visitLineNumber(998, label84)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label89 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label89)
        val label90 = Label()
        methodVisitor.visitLabel(label90)
        methodVisitor.visitLineNumber(999, label90)
        methodVisitor.visitIincInsn(7, 1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label89)
        methodVisitor.visitLabel(label78)
        methodVisitor.visitLineNumber(1003, label78)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 46)
        val label91 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label91)
        val label92 = Label()
        methodVisitor.visitLabel(label92)
        methodVisitor.visitLineNumber(1005, label92)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        val label93 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label93)
        val label94 = Label()
        methodVisitor.visitLabel(label94)
        methodVisitor.visitLineNumber(1006, label94)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label93)
        methodVisitor.visitLineNumber(1007, label93)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 12)
        val label95 = Label()
        methodVisitor.visitLabel(label95)
        methodVisitor.visitLineNumber(1008, label95)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label89)
        methodVisitor.visitLabel(label91)
        methodVisitor.visitLineNumber(1011, label91)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 101)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label73)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 15)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 69)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label73)
        val label96 = Label()
        methodVisitor.visitLabel(label96)
        methodVisitor.visitLineNumber(1012, label96)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label89)
        methodVisitor.visitLineNumber(979, label89)
        methodVisitor.visitIincInsn(2, 1)
        methodVisitor.visitIincInsn(3, -1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label72)
        methodVisitor.visitLabel(label73)
        methodVisitor.visitLineNumber(1017, label73)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label1)
        val label97 = Label()
        methodVisitor.visitLabel(label97)
        methodVisitor.visitLineNumber(1018, label97)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label1)
        methodVisitor.visitLineNumber(1026, label1)
        val label98 = Label()
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label98)
        methodVisitor.visitLabel(label2)
        methodVisitor.visitLineNumber(1024, label2)
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 11)
        val label99 = Label()
        methodVisitor.visitLabel(label99)
        methodVisitor.visitLineNumber(1025, label99)
        methodVisitor.visitTypeInsn(Opcodes.NEW, "java/lang/NumberFormatException")
        methodVisitor.visitInsn(Opcodes.DUP)
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/NumberFormatException",
            "<init>",
            "()V",
            false
        )
        methodVisitor.visitInsn(Opcodes.ATHROW)
        methodVisitor.visitLabel(label98)
        methodVisitor.visitLineNumber(1028, label98)
        methodVisitor.visitInsn(Opcodes.RETURN)
        val label100 = Label()
        methodVisitor.visitLabel(label100)
        methodVisitor.visitLocalVariable("digit", "I", null, label39, label43, 18)
        methodVisitor.visitLocalVariable("digit", "I", null, label51, label61, 18)
        methodVisitor.visitLocalVariable("c", "C", null, label27, label25, 15)
        methodVisitor.visitLocalVariable("mcp", "I", null, label70, label71, 18)
        methodVisitor.visitLocalVariable("c", "C", null, label75, label73, 15)
        methodVisitor.visitLocalVariable("coeff", "[C", null, label72, label1, 18)
        methodVisitor.visitLocalVariable("isneg", "Z", null, label11, label1, 11)
        methodVisitor.visitLocalVariable("dot", "Z", null, label19, label1, 12)
        methodVisitor.visitLocalVariable("exp", "J", null, label20, label1, 13)
        methodVisitor.visitLocalVariable("isCompact", "Z", null, label21, label1, 16)
        methodVisitor.visitLocalVariable("idx", "I", null, label22, label1, 17)
        methodVisitor.visitLocalVariable(
            "e",
            "Ljava/lang/RuntimeException;",
            null,
            label99,
            label98,
            11
        )
        methodVisitor.visitLocalVariable("in", "[C", null, label4, label100, 1)
        methodVisitor.visitLocalVariable("offset", "I", null, label5, label100, 2)
        methodVisitor.visitLocalVariable("len", "I", null, label6, label100, 3)
        methodVisitor.visitLocalVariable("MAX_COMPACT_DIGITS", "I", null, label7, label100, 5)
        methodVisitor.visitLocalVariable("prec", "I", null, label8, label100, 6)
        methodVisitor.visitLocalVariable("scl", "I", null, label9, label100, 7)
        methodVisitor.visitLocalVariable("rs", "J", null, label10, label100, 8)
        methodVisitor.visitLocalVariable("rb", "Ljava/math/BigInteger;", null, label0, label100, 10)
        methodVisitor.visitMaxs(4, 20)
        methodVisitor.visitEnd()
    }

}