package com.mckj.junkCode.templates.add

import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * Template5
 *
 * @author mmxm
 * @date 2023/7/11 15:42
 */
object Template5 {
    fun fillfromCode(methodVisitor: MethodVisitor) {
        methodVisitor.visitCode()
        val label0 = Label()
        methodVisitor.visitLabel(label0)
        methodVisitor.visitLineNumber(447, label0)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 1)
        val label1 = Label()
        methodVisitor.visitLabel(label1)
        methodVisitor.visitLineNumber(448, label1)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 10)
        methodVisitor.visitIntInsn(Opcodes.NEWARRAY, Opcodes.T_BYTE)
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 2)
        val label2 = Label()
        methodVisitor.visitLabel(label2)
        methodVisitor.visitLineNumber(449, label2)
        methodVisitor.visitInsn(Opcodes.ICONST_0)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 3)
        val label3 = Label()
        methodVisitor.visitLabel(label3)
        methodVisitor.visitLineNumber(450, label3)
        methodVisitor.visitIntInsn(Opcodes.BIPUSH, 10)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 4)
        val label4 = Label()
        methodVisitor.visitLabel(label4)
        methodVisitor.visitLineNumber(451, label4)
        methodVisitor.visitInsn(Opcodes.ACONST_NULL)
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        val label5 = Label()
        methodVisitor.visitLabel(label5)
        methodVisitor.visitLineNumber(453, label5)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitInsn(Opcodes.BALOAD)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitInsn(Opcodes.IAND)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
        val label6 = Label()
        methodVisitor.visitLabel(label6)
        methodVisitor.visitLineNumber(454, label6)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitInsn(Opcodes.ICONST_1)
        methodVisitor.visitInsn(Opcodes.IADD)
        methodVisitor.visitInsn(Opcodes.BALOAD)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitInsn(Opcodes.IAND)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 7)
        val label7 = Label()
        methodVisitor.visitLabel(label7)
        methodVisitor.visitLineNumber(455, label7)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitInsn(Opcodes.ICONST_2)
        methodVisitor.visitInsn(Opcodes.IADD)
        methodVisitor.visitInsn(Opcodes.BALOAD)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitInsn(Opcodes.IAND)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 8)
        val label8 = Label()
        methodVisitor.visitLabel(label8)
        methodVisitor.visitLineNumber(456, label8)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitInsn(Opcodes.ICONST_3)
        methodVisitor.visitInsn(Opcodes.IADD)
        methodVisitor.visitInsn(Opcodes.BALOAD)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitInsn(Opcodes.IAND)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 9)
        val label9 = Label()
        methodVisitor.visitLabel(label9)
        methodVisitor.visitLineNumber(458, label9)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
        val label10 = Label()
        val label11 = Label()
        val label12 = Label()
        val label13 = Label()
        val label14 = Label()
        methodVisitor.visitLookupSwitchInsn(
            label14,
            intArrayOf(0, 239, 254, 255),
            arrayOf(label10, label11, label12, label13)
        )
        methodVisitor.visitLabel(label11)
        methodVisitor.visitLineNumber(460, label11)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 187)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 191)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        val label15 = Label()
        methodVisitor.visitLabel(label15)
        methodVisitor.visitLineNumber(461, label15)
        methodVisitor.visitLdcInsn("UTF_8")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label12)
        methodVisitor.visitLineNumber(465, label12)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        val label16 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label16)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label16)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 9)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label16)
        val label17 = Label()
        methodVisitor.visitLabel(label17)
        methodVisitor.visitLineNumber(466, label17)
        methodVisitor.visitLdcInsn("ISO_10646_UCS_4_3412")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label16)
        methodVisitor.visitLineNumber(467, label16)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        val label18 = Label()
        methodVisitor.visitLabel(label18)
        methodVisitor.visitLineNumber(468, label18)
        methodVisitor.visitLdcInsn("UTF_16BE")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label10)
        methodVisitor.visitLineNumber(472, label10)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        val label19 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label19)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 254)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label19)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 9)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label19)
        val label20 = Label()
        methodVisitor.visitLabel(label20)
        methodVisitor.visitLineNumber(473, label20)
        methodVisitor.visitLdcInsn("UTF_32BE")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label19)
        methodVisitor.visitLineNumber(474, label19)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label14)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 9)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 254)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        val label21 = Label()
        methodVisitor.visitLabel(label21)
        methodVisitor.visitLineNumber(475, label21)
        methodVisitor.visitLdcInsn("ISO_10646_UCS_4_2143")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label13)
        methodVisitor.visitLineNumber(479, label13)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 254)
        val label22 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label22)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label22)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 9)
        methodVisitor.visitJumpInsn(Opcodes.IFNE, label22)
        val label23 = Label()
        methodVisitor.visitLabel(label23)
        methodVisitor.visitLineNumber(480, label23)
        methodVisitor.visitLdcInsn("UTF_32LE")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
        methodVisitor.visitLabel(label22)
        methodVisitor.visitLineNumber(481, label22)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 254)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label14)
        val label24 = Label()
        methodVisitor.visitLabel(label24)
        methodVisitor.visitLineNumber(482, label24)
        methodVisitor.visitLdcInsn("UTF_16LE")
        methodVisitor.visitVarInsn(Opcodes.ASTORE, 5)
        methodVisitor.visitLabel(label14)
        methodVisitor.visitLineNumber(487, label14)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 5)
        val label25 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFNULL, label25)
        val label26 = Label()
        methodVisitor.visitLabel(label26)
        methodVisitor.visitLineNumber(488, label26)
        methodVisitor.visitInsn(Opcodes.RETURN)
        methodVisitor.visitLabel(label25)
        methodVisitor.visitLineNumber(490, label25)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 4)
        methodVisitor.visitInsn(Opcodes.IADD)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 10)
        val label27 = Label()
        methodVisitor.visitLabel(label27)
        methodVisitor.visitLineNumber(491, label27)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 3)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 11)
        val label28 = Label()
        methodVisitor.visitLabel(label28)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 11)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 10)
        val label29 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPGE, label29)
        val label30 = Label()
        methodVisitor.visitLabel(label30)
        methodVisitor.visitLineNumber(492, label30)
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 11)
        methodVisitor.visitInsn(Opcodes.BALOAD)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 255)
        methodVisitor.visitInsn(Opcodes.IAND)
        methodVisitor.visitVarInsn(Opcodes.ISTORE, 12)
        val label31 = Label()
        methodVisitor.visitLabel(label31)
        methodVisitor.visitLineNumber(493, label31)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 128)
        methodVisitor.visitInsn(Opcodes.IAND)
        val label32 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IFEQ, label32)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 12)
        methodVisitor.visitIntInsn(Opcodes.SIPUSH, 160)
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label32)
        val label33 = Label()
        methodVisitor.visitLabel(label33)
        methodVisitor.visitLineNumber(494, label33)
        methodVisitor.visitVarInsn(Opcodes.ILOAD, 1)
        methodVisitor.visitInsn(Opcodes.ICONST_2)
        val label34 = Label()
        methodVisitor.visitJumpInsn(Opcodes.IF_ICMPEQ, label34)
        val label35 = Label()
        methodVisitor.visitLabel(label35)
        methodVisitor.visitLineNumber(495, label35)
        methodVisitor.visitFieldInsn(
            Opcodes.GETSTATIC,
            "java/lang/System",
            "out",
            "Ljava/io/PrintStream;"
        )
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/io/PrintStream",
            "println",
            "()V",
            false
        )
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label34)
        methodVisitor.visitLabel(label32)
        methodVisitor.visitLineNumber(498, label32)
        methodVisitor.visitFieldInsn(
            Opcodes.GETSTATIC,
            "java/lang/System",
            "out",
            "Ljava/io/PrintStream;"
        )
        methodVisitor.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            "java/io/PrintStream",
            "println",
            "()V",
            false
        )
        methodVisitor.visitLabel(label34)
        methodVisitor.visitLineNumber(491, label34)
        methodVisitor.visitIincInsn(11, 1)
        methodVisitor.visitJumpInsn(Opcodes.GOTO, label28)
        methodVisitor.visitLabel(label29)
        methodVisitor.visitLineNumber(502, label29)
        methodVisitor.visitInsn(Opcodes.RETURN)
        val label36 = Label()
        methodVisitor.visitLabel(label36)
        methodVisitor.visitLocalVariable("c", "I", null, label31, label34, 12)
        methodVisitor.visitLocalVariable("i", "I", null, label28, label29, 11)
        methodVisitor.visitLocalVariable("inputState", "I", null, label1, label36, 1)
        methodVisitor.visitLocalVariable("buf", "[B", null, label2, label36, 2)
        methodVisitor.visitLocalVariable("offset", "I", null, label3, label36, 3)
        methodVisitor.visitLocalVariable("length", "I", null, label4, label36, 4)
        methodVisitor.visitLocalVariable(
            "detectedCharset",
            "Ljava/lang/String;",
            null,
            label5,
            label36,
            5
        )
        methodVisitor.visitLocalVariable("b1", "I", null, label6, label36, 6)
        methodVisitor.visitLocalVariable("b2", "I", null, label7, label36, 7)
        methodVisitor.visitLocalVariable("b3", "I", null, label8, label36, 8)
        methodVisitor.visitLocalVariable("b4", "I", null, label9, label36, 9)
        methodVisitor.visitLocalVariable("maxPos", "I", null, label27, label36, 10)
        methodVisitor.visitMaxs(3, 13)
        methodVisitor.visitEnd()
    }

}